SELECT CONCAT('ALTER TABLE ',i.TABLE_NAME,' CHANGE ',i.COLUMN_NAME,' ',i.COLUMN_NAME,' ',i.COLUMN_TYPE,' COMMENT "',i.COLUMN_COMMENT,'";')
FROM INFORMATION_SCHEMA.COLUMNS i
WHERE TABLE_SCHEMA = 'foot_001' ;